### ISSUE TITLE
OS requirement 

### ISSUE THREAD

**Issue by jvtrudel** [coopsymbiotic/coopsymbiotic-ansible#1]
What is the required OS to run your playbooks? Is Debian 10 ready to use in production? Is Debian 9 still supported?

In the `README.md`:

> ...
> The server from where you will be running Ansible must have Ansible >= 2.0 on Debian 9.
> ...

In `roles/common-all/tasks/main.yml`:

> ...
> \# Not required since Debian10
> ...

**Comment by mlutfy** [comment]
Hi @jvtrudel, Debian 10 is our current target OS. I did a few edits to the README to clarify.

**Comment by jvtrudel** [comment]
Thanks
